---
- name: copy resolv.conf
  template: src=resolv.conf dest=/etc/resolv.conf
  tags: dns
- name: subscribe and register specific pool bi ID
  redhat_subscription:
   state: present
   username: Wipro_DCC
   password: opendc78901
   pool: 8a85f98158a4693d0158aa5ba25f5665
