---

- name: Enabling OSPF feature
  nxos_feature:
    feature: ospf
    state: enabled


- name: Enable L3 Port
  nxos_interface:
    interface: "{{interface}}"
    mode: layer3

- name: Enable OSPF
  nxos_command:
    commands:
       - conf t
       - router ospf {{ process_id }}
       - area {{area }} default-cost {{cost}}
       - interface {{interface}}
       - ip router ospf {{process_id}} area {{area}}
       - exit
       - exit

