---
- include_vars: win_cred.yml
- name: copying NSCP Packege to host.
  win_copy:
    src: /var/lib/awx/projects/nagios_windows/windows_package/NSCP-0.4.1.73-x64.msi
    dest: C:\Users\Administrator\Desktop\
- name: installing NSCP package
  win_package:
    path: C:\Users\Administrator\Desktop\NSCP-0.4.1.73-x64.msi
    state: present
    product_id: no
  ignore_errors: yes
- name: deleting old nsclient.ini
  win_file:
    path: C:\Program Files\NSClient++\nsclient.ini
    state: absent
- name: copying .ini file.
  win_copy:
    src: /var/lib/awx/projects/nagios_windows/windows_package/nsclient.ini
    dest: C:\Program Files\NSClient++
- name: Restarting NSCP service
  win_service:
    name: nscp
    state: restarted
  #when: ansible_os_family == 'Windows'
