---
#- name: Copy hosts
#  template: src=/var/lib/awx/projects/commvault/roles/commvault/tasks/hosts dest=/etc/hosts
#  ignore_errors: True  
- name: Copy commvault.rb file 
  template: src=/var/lib/awx/projects/commvault/roles/commvault/tasks/commvault.rb dest=/tmp/commvault.rb
- name: copy Commvault directory
  synchronize:
    src:  /root/commvault/
    dest: /root/commvault/
  delegate_to: 172.17.65.22  
- name: Installing Commvault
  shell: /root/commvault/DownloadPackageLocationAug/silent_install -p /root/commvault/UnixCustomPackage1/pkg/default.xml
  ignore_errors: True
- name: Registering and applying Backup Policy
  shell: /usr/bin/ruby /tmp/commvault.rb "{{ server_name }}" "{{ bkp_policy }}" 
#- name: Appending /etc/hosts file in backup server
#  win_lineinfile:
#    path: C:\Windows\System32\drivers\etc\hosts
#    line: 172.17.65.91  {{ server_name }}
#- name: Appending /etc/hosts file in backup server
#  shell: /usr/bin/ruby /var/tmp/dns.rb 172.17.65.91 "{{ server_name }}"

