---
- name: Create a VM from a rhel template
  vmware_guest:
    hostname: 172.17.66.156
    username: administrator@vsphere.local
    password: Wipro@123
    validate_certs: no
    datacenter: Devops
    name: mysqlserver1
    state: poweredon
    cluster: Openshift
    template: RHEL7.3_temp
    disk:
    - size_gb: 50
      type: thin
      datastore: datastore1
    hardware:
      memory_mb: 6000
      num_cpus: 3
      scsi: paravirtual
    networks:
    - name: VM Network
      device_type: vmxnet3
      type: static
      ip : 172.17.65.91
      netmask: 255.255.255.0
      gateway: 172.17.65.1
    wait_for_ip_address: no
  delegate_to: localhost
  register: deploy
- pause:
    seconds: 150
