---
- name: Create Database
  rds:
    aws_access_key: AKIAIVTGUHE6OZJPAY7A
    aws_secret_key: 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
    region: us-east-1
    command: create
    instance_name: new-database
    db_engine: MySQL
    size: 10
    instance_type: db.m1.small
    username: mysql_admin
    password: 1nsecure
    tags:
      Environment: testing
      Application: cms 
