---

- hosts: oracle_new

  tasks:
  - name: Run installer to install oracle
    command: /home/oracle/Oracle11.2.0.4/database/runInstaller -silent -ignorePrereq -ignoreSysPrereqs -waitforcompletion -responseFile /home/oracle/Oracle11.2.0.4/database/AutomateInstallation.rsp
    ignore_errors: True
