---
- name: Listing QoS group in the cloudbyte storage
  hosts: localhost
  gather_facts: no
  vars:
    apikey: V-RDsMsLIn84TVjcJkWAyvdxhj5LYHpfpm6UzdhVJ1dWMxzN3Bcd_guGkiljA9JodnMTu-USUro7VaYoZgx8gw
    command: listAccount
  tasks:
    - name: List Account
      uri:
        url: https://172.16.6.21/client/api?command={{ command }}&apiKey={{ apikey }}
        method: GET
        validate_certs: no
        return_content: yes
        body_format: json
      register: qosgroup

    - name: List Account
      debug: var=qosgroup

