- name: Create a security group and assign Rules
  os_security_group_rule:
       state: present
       auth:
         auth_url: http://172.17.77.108:35357/v2.0
         username: admin
         password: Wipro@123
         project_name: admin
       security_group: foo
       protocol: icmp
       remote_ip_prefix: 0.0.0.0/0
