- name: Create an externally accessible network named 'ext_network'.
  os_nova_flavor:
       state: present
       auth:
         auth_url: http://172.17.77.108:35357/v2.0
         username: admin
         password: Wipro@123
         project_name: admin
       name: tiny
       ram: 1024
       vcpus: 1
       disk: 10
       ephemeral: 10
