---

- hosts: leaf 
  connection: local
   
  vars: 
   fname: "{{fname}}"
   faction: "{{faction}}" 

  tasks:
    - name: configuring feature    
      nxos_feature: 
         feature: "{{fname}}"
         state: "{{faction}}"
