---

- hosts: leaf
  connection: local
  
  vars:
    pid: "{{pid}}"
    area: "{{area}}"
    cost: "{{cost}}"
    intf: "{{intf}}"
   
  tasks:
    - name: Enabling OSPF feature
      nxos_feature:
         feature: ospf
         state: enabled
    
    - name: OSPF Configuration
      nxos_command: 
         commands: 
            - conf t
            - router ospf {{pid}}
            - area {{area}} default-cost {{cost}}
            - interface {{intf}}
            - ip router ospf {{pid}} area {{area}}
            - exit
            - exit   
