---
- hosts: localhost
  tasks:
  - name: Create a VM from a template
    vmware_guest:
      hostname: 172.17.66.156
      username: administrator@vsphere.local
      password: Wipro@123
      validate_certs: no
      datacenter: Devops
      cluster: Openshift
      name: windows_test
      state: poweredon
      template: WindowsNew_temp
      customization:
        password: Wipro@123
      disk:
      - size_gb: 50
        type: thin
        datastore: datastore1
      hardware:
        memory_mb: 4096
        num_cpus: 2
        scsi: paravirtual
      networks:
      - name: VM Network
        device_type: vmxnet3
        type: static
        ip : 172.17.65.175
        netmask: 255.255.255.0
        gateway: 172.17.65.1
      wait_for_ip_address: no
    delegate_to: localhost
    register: deploy

  - pause:
      seconds: 45
