---
- name: create folder
  file:
    path: /root/nagios
    state: directory
- name: copy file to client hosts
  synchronize:
    src: /var/lib/awx/projects/nagios_linux/nagios_package/
    dest: /root/nagios/
  delegate_to: 172.17.65.22  
- name: Creating Nagios User.
  user:  name=nagios password=nagios
  #tasks:
- name: installing Packages.
  yum: pkg={{item}} state=installed
  with_items:
    - gcc
    - glibc
    - glibc-common
    - openssl
    - openssl-devel
    - perl
    - wget
    - gd 
    - gd-devel
    - make 
    - net-snmp
  ignore_errors: yes  
  #tasks:
- name: installing nagios plugins
  command: "{{ item }} chdir=/root/nagios/nagios-plugins-2.2.1/"
  with_items:
    - ./configure
    - make
    - make install
    - chown nagios.nagios /usr/local/nagios
    - chown -R nagios.nagios /usr/local/nagios/libexec
  #tasks:
- name: installing xinetd Packages.
  yum: pkg=xinetd state=installed
  #tasks:
- name: installing NRPE.
  command: "{{ item }} chdir=/root/nagios/nrpe-nrpe-3.2.1/"
  with_items:
    - ./configure --enable-command-args
    - make all
    - make install
    - make install-config
- name: adding port.
  command: echo 'nrpe    5666/tcp' >> /etc/services
- name: starting NRPE Services
  command: "{{ item }} chdir=/root/nagios/nrpe-nrpe-3.2.1/"
  with_items: 
    - make install-init
    - systemctl enable nrpe.service
  #tasks:
- name: firewall configuration for port 5666.
  command: "{{ item }}"
  with_items:
    - firewall-cmd --zone=public --add-port=5666/tcp
    - firewall-cmd --zone=public --add-port=5666/tcp --permanent
  ignore_errors: yes  
- name: configuring NRPE file.
  command: "{{ item }}"
  with_items:
    - cp /usr/local/nagios/etc/nrpe.cfg /usr/local/nagios/etc/nrpe.cfg.bkp
    - sed -i '/^allowed_hosts=/s/$/,172.17.65.214/' /usr/local/nagios/etc/nrpe.cfg
    - sed -i 's/^dont_blame_nrpe=.*/dont_blame_nrpe=1/g' /usr/local/nagios/etc/nrpe.cfg
 #tasks:
- name: Starting NRPE Services
  service:
    name: nrpe
    state: restarted
  #tasks:
- name: checking NRPE Versio
  command: /usr/local/nagios/libexec/check_nrpe -H 127.0.0.1
  register: NRPE_Version
- debug: var=NRPE_Version.stdout_lines
        
