---
- hosts: windows1
  tasks:
  - name: Deploy guest from template
    vsphere_guest:
      vcenter_hostname: 172.17.66.156
      username: Administrator@vsphere.local
      password: Wipro@123
      guest: clone1
      from_template: yes
      template_src: Win2K12
      cluster: Openshift
