---
- hosts: localhost
  tasks:
  - name: Create a VM from a template
    vmware_guest:
      hostname: 172.17.66.156
      username: administrator@vsphere.local
      password: Wipro@123
      validate_certs: no
      datacenter: Devops
      name: "{{ item }}"
      #exact_count: "{{ count }}"
      state: poweredon
      template: RHEL7.3_temp
      disk:
      - size_gb: 50
        type: thin
        datastore: datastore1
      - size_gb: 50
        type: thin
        datastore: datastore1
      hardware:
        memory_mb: 2048
        num_cpus: 1
        scsi: paravirtual
      networks:
      - name: VM Network
        device_type: vmxnet3
        type: dhcp
        #type: static
        #ip : "" #172.17.65.115
        #netmask: "" #255.255.255.0
        #gateway: "" #172.17.65.1
      wait_for_ip_address: no
    delegate_to: localhost
    register: deploy
    with_items:
      - test2
      - test3

  - pause:
      seconds: 45
