---

- name: create user
  mysql_user:
#    name: "{{ db_user }}"
    name: dbadmin
    host: "{{ item }}"
#    password: "{{ db_password }}"
    password: Wipro@123
    state: present

  with_items:
    - localhost
    - 127.0.0.1
    - ::1



