---
- hosts: 172.17.66.156
  tasks:
  - name: Create a VM from a template
    vmware_guest:
      hostname: 172.17.66.156
      username: administrator@vsphere.local
      password: Wipro@123
      validate_certs: no
  #    folder: /Devops/Testvms
      datacenter: Devops
      name: hardner_os
      state: poweredon
      template: RHEL7.3_temp
      disk:
      - size_gb: 50
        type: thin
        datastore: datastore1
      hardware:
        memory_mb: 2048
        num_cpus: 1
        scsi: paravirtual
      networks:
      - name: VM Network
 #       mac: 00:50:56:87:a6:b1
      wait_for_ip_address: yes
    delegate_to: localhost
    register: deploy
