---
- name: Create a VM from a rhel template
  vmware_guest:
    hostname: 172.17.66.156
    username: administrator@vsphere.local
    password: Wipro@123
    validate_certs: no
    datacenter: Devops
    name: "{{ server_name }}"
    state: poweredon
    template: RHEL7.3_temp
    disk:
    - size_gb: "{{ disk_size }}"
      type: thin
      datastore: datastore1
    hardware:
      memory_mb: "{{ mem }}"
      num_cpus: "{{ cpu }}"
      scsi: paravirtual
    networks:
    - name: VM Network
      device_type: vmxnet3
      type: static
      ip : 172.17.65.93
      netmask: 255.255.255.0
      gateway: 172.17.65.1
    wait_for_ip_address: no
  delegate_to: localhost
  register: deploy
  when:  (os == "rhel" and env == "prod")
- name: Create a VM from a rhel template
  vmware_guest:
    hostname: 172.17.66.156
    username: administrator@vsphere.local
    password: Wipro@123
    validate_certs: no
    datacenter: Devops
    name: "{{ server_name }}"
    state: poweredon
    template: RHEL7.3_temp
    disk:
    - size_gb: "{{ disk_size }}"
      type: thin
      datastore: datastore1
    hardware:
      memory_mb: "{{ mem }}"
      num_cpus: "{{ cpu }}"
      scsi: paravirtual
    networks:
    - name: VM Network
      device_type: vmxnet3
      type: static
      ip : 172.17.65.93
      netmask: 255.255.255.0
      gateway: 172.17.65.1
    wait_for_ip_address: no
  delegate_to: localhost
  register: deploy
  when:  (os == "rhel" and env == "dev")
- name: Create a VM from a rhel template
  vmware_guest:
    hostname: 172.17.66.156
    username: administrator@vsphere.local
    password: Wipro@123
    validate_certs: no
    datacenter: Devops
    name: "{{ server_name }}"
    state: poweredon
    template: RHEL7.3_temp
    disk:
    - size_gb: "{{ disk_size }}"
      type: thin
      datastore: datastore1
    hardware:
      memory_mb: "{{ mem }}"
      num_cpus: "{{ cpu }}"
      scsi: paravirtual
    networks:
    - name: VM Network
      device_type: vmxnet3
      type: static
      ip : 172.17.65.93
      netmask: 255.255.255.0
      gateway: 172.17.65.1
    wait_for_ip_address: no
  delegate_to: localhost
  register: deploy
  when:  (os == "rhel" and env == "test")

- name: Create a centos VM from a template
  vmware_guest:
    hostname: 172.17.66.156
    username: administrator@vsphere.local
    password: Wipro@123
    validate_certs: no
    datacenter: Devops
    name: "{{ server_name }}"
    state: poweredon
    template: Centos_7_CPU_2_Memory_6G_HDD_50G
    disk:
    - size_gb: "{{ disk_size }}"
      type: thin
      datastore: datastore1
    hardware:
      memory_mb: "{{ mem }}"
      num_cpus: "{{ cpu }}"
      scsi: paravirtual
    networks:
    - name: VM Network
      device_type: vmxnet3
      type: static
      ip : 172.17.65.93
      netmask: 255.255.255.0
      gateway: 172.17.65.1
    wait_for_ip_address: no
  delegate_to: localhost
  register: deploy
  when: (os == "centos" and env == "prod") 
- name: Create a centos VM from a template
  vmware_guest:
    hostname: 172.17.66.156
    username: administrator@vsphere.local
    password: Wipro@123
    validate_certs: no
    datacenter: Devops
    name: "{{ server_name }}"
    state: poweredon
    template: Centos_7_CPU_2_Memory_6G_HDD_50G
    disk:
    - size_gb: "{{ disk_size }}"
      type: thin
      datastore: datastore1
    hardware:
      memory_mb: "{{ mem }}"
      num_cpus: "{{ cpu }}"
      scsi: paravirtual
    networks:
    - name: VM Network
      device_type: vmxnet3
      type: static
      ip : 172.17.65.93
      netmask: 255.255.255.0
      gateway: 172.17.65.1
    wait_for_ip_address: no
  delegate_to: localhost
  register: deploy
  when:  (os == "centos" and env == "dev")
- name: Create a centos VM from a template
  vmware_guest:
    hostname: 172.17.66.156
    username: administrator@vsphere.local
    password: Wipro@123
    validate_certs: no
    datacenter: Devops
    name: "{{ server_name }}"
    state: poweredon
    template: Centos_7_CPU_2_Memory_6G_HDD_50G
    disk:
    - size_gb: "{{ disk_size }}"
      type: thin
      datastore: datastore1
    hardware:
      memory_mb: "{{ mem }}"
      num_cpus: "{{ cpu }}"
      scsi: paravirtual
    networks:
    - name: VM Network
      device_type: vmxnet3
      type: static
      ip : 172.17.65.93
      netmask: 255.255.255.0
      gateway: 172.17.65.1
    wait_for_ip_address: no
  delegate_to: localhost
  register: deploy
  when:  (os == "centos" and env == "test") 

- pause:
    seconds: 150
