---
- hosts: localhost
  tasks:
  - name: Create a VM from a template
    vmware_guest:
      hostname: 172.17.66.156
      username: administrator@vsphere.local
      password: Wipro@123
      validate_certs: no
      datacenter: Devops
      cluster: Openshift
      name: "{{ vm_name }}"
      state: poweredon
      template: Win2K12
      customization:
        password: Wipro@123
      disk:
      - size_gb: "{{ disk_size }}"
        type: thin
        datastore: datastore1
      hardware:
        memory_mb: "{{ ram_size }}"
        num_cpus: "{{ cpu_count }}"
        scsi: paravirtual
      networks:
      - name: "{{ port_group }}"
        device_type: vmxnet3
        type: static
        ip : 172.17.65.173
        netmask: 255.255.255.0
        gateway: 172.17.65.1
      wait_for_ip_address: no
    delegate_to: localhost
    register: deploy

  - pause:
      seconds: 45

