---
- hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: lamp_host
      prompt: please enter servers IP where lamp should install 
      private: no
  tasks:
    - add_host:
        name: "{{ lamp_host }}"
        groups: lamp

- hosts: lamp
  become: yes
  become_user: root

  roles:
  - lamp
