---
- hosts: localhost
  pre_tasks:
  - name: Create a VM from a template
    vmware_guest:
      hostname: 172.17.66.156
      username: administrator@vsphere.local
      password: Wipro@123
      validate_certs: no
      datacenter: Devops
      name: hardenos
      state: poweredon
      template: RHEL7.3_temp
      disk:
      - size_gb: 100
        type: thin
        datastore: datastore1
      hardware:
        memory_mb: 4096
        num_cpus: 2
        scsi: paravirtual
      networks:
      - name: VM Network
        vlan: 2
        device_type: vmxnet3
        type: static
        ip : 172.17.65.198
        netmask: 255.255.255.0
        gateway: 172.17.65.1
      wait_for_ip_address: yes
    delegate_to: localhost
    register: deploy
  
  - pause:
      seconds: 45

- hosts: 172.17.65.198
  post_tasks:
  - name: Copy Resolve.conf file
    copy: src=/var/lib/awx/projects/mysql-server/roles/mysql-server/templates/resolv.conf dest=/etc/resolv.conf
  - name: creating the folder
    file:
      path: /root/hardning
      state: directory
      mode: 0777
  
  - name: transfer script to hosts
    copy: src=/root/openshift/roles/vmware_guest_mysql/tasks/guest_vm/Linux_Hardening/Linux_Hardening.sh dest=/root/hardning/ mode=0777

  - name: Execute the script
    command: sh /root/hardning/Linux_Hardening.sh

