---
- hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: wordpress_host
      prompt: please enter servers IP where wordpress should install
      private: no
  tasks:
    - add_host:
        name: "{{ wordpress_host }}"
        groups: wordpress
    
- hosts: wordpress
  become: yes
  become_user: root

  roles:
  - wordpress
