---
- name:
  file:
    path: /root/tmp
    state: touch
    mode: 0644
- name: adding host in host file.
  blockinfile:
    path: /root/tmp
    block: |
      ## Default
      define host{
      use                             windows-server               ; Inherit default values from a template
      host_name                       {{ client_hostname }}                  ; The name we're giving to this server
      alias                           My Windows Server                ; A longer name for the server
      address                         {{ nagios_clientIP }}            ; IP address of Remote Linux host
      }
- name: appending the files
  shell: cat /root/tmp >> //usr/local/nagios/etc/windows_hosts.cfg
- name: removing tmp
  file:
    path: /root/tmp
    state: absent
- name: adding host to group
  shell: sed -i 's/WIN-NPB5U34C123/WIN-NPB5U34C123,{{ client_hostname }}/' /usr/local/nagios/etc/hosts_group.cfg
- name: Restart nagios service.
  service:
     name: nagios
     state: restarted
