---
# setup tasks for the scaleio environment

# now run all the commands to start the basic stup
- name: login to scaleIO with default credentials
  command: scli --login --username admin --password admin --accept_banner_by_scripts_only --approve_certificate

- name: login reset default credentials
  command: scli --set_password --old_password admin --new_password Wipro@123

- name: login with new credentials
  command: scli --login --username admin --password Wipro@123

- name: Generate MDM Certificate
  command: echo yes | scli --generate_mdm_certificate --target_mdm_ip {{ pdm }} --target_mdm_port 9011

- name: Approve  MDM Certificate
  command: echo yes | scli --approve_all_mdm_certificates

#- name: Create MDM cluster
#  command: scli --create_mdm_cluster --master_mdm_ip {{ pdm }} --disable_client_secure_communication --accept_license
#  ignore_errors: yes
 
- name: Add standby MDM
  command: scli --add_standby_mdm --mdm_role manager --new_mdm_ip {{ sdm }}

- name: Add tie breaker
  command: scli --add_standby_mdm --mdm_role tb --new_mdm_ip {{ tb }}

- name: Adding secondary MDM and tie breaker
  command: scli --switch_cluster_mode --cluster_mode 3_node --add_slave_mdm_ip {{ sdm }} --add_tb_ip {{ tb }} 

- name: Creating protection domain
  command: scli --mdm_ip {{ pdm }} --add_protection_domain --protection_domain_name PD01

- name: Creating Storage Pool
  command: scli --mdm_ip {{ pdm }} --add_storage_pool --protection_domain_name {{ pdn }} --storage_pool_name {{ spn }}

- name: Add mdm sds device
  command: scli --mdm_ip {{ pdm }} --add_sds --sds_ip {{ pdm }} --sds_ip_role all --protection_domain_name {{ pdn }} --storage_pool_name {{ spn }} --device_path /dev/sdb --device_name sds01 --sds_name mdm
  
- name: Add sds  sds device
  command: scli --mdm_ip {{ pdm }} --add_sds --sds_ip {{ sdm }} --sds_ip_role all --protection_domain_name {{ pdn }} --storage_pool_name {{ spn }} --device_path /dev/sdb --device_name sds02 --sds_name sds1
  
- name: Add tb sds device
  command: scli --mdm_ip {{ pdm }} --add_sds --sds_ip {{ tb }} --sds_ip_role all --protection_domain_name {{ pdn }} --storage_pool_name {{ spn }} --device_path /dev/sdb --device_name sds03 --sds_name sds2
  
#- name: Add storage from sds
#  debug: msg="scli --mdm_ip {{ pdm }} --add_sds --sds_ip {{ item.sds_ip }} --sds_ip_role all --protection_domain_name PD01 --storage_pool_name SP01 --device_path /dev/sdb --device_name {{item.sds_device_name }} --sds_name {{ item.sds_name }}"
#  with_items:
#    - { sds_ip: '172.17.65.86', sds_device_name: 'sds0', sds_name: 'mdm_sds'} 
#    - { sds_ip: '172.17.65.87', sds_device_name: 'sds1', sds_name: 'sds1_sds'} 
#    - { sds_ip: '172.17.65.88', sds_device_name: 'sds2', sds_name: 'sds2_sds'} 
