---
- hosts: 172.17.65.11
  tasks:
  - name: Delete a portgroup with vlan
    local_action:
      module: vmware_portgroup
      hostname: 172.17.65.11
      username: root
      password: Wipro@123
      switch_name: "{{ vSwitch0 }}"
      portgroup_name: "{{ test_port2 }}"
      vlan_id: "{{ 007 }}" 
